{% set name = "erddapy" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erddapy-{{ version }}.tar.gz
  sha256: ebcd1a1d50ba458f5336d53ad1a0a00a5e308f8e7c374840bbb2ea13f97ae491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - httpx
    - pandas <3,>=0.25.2
    - pytz

test:
  imports:
    - erddapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
