{% set version = "1.1.0" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: c12d3919f6f53e6049f0cf67f48b94748aa017f48fd3c50279c9ef12d911aa11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - pip
    - setuptools_scm
  run:
    - python >=3.6,<4
    - pandas >=0.20.3
    - requests

test:
  requires:
    - pip
  imports:
    - erddapy
  commands:
    - pip check

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
