{% set version = "0.1.8" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 97a45006a29d78f38c97b64127529c9802109b2b0a49448f61e23cbbbc5b5a89

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
