{% set version = "0.1.10" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: ccea05ef93e2b2a2409b24d96a654a2944c1c8a172cd70fa328241687b920012

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
