{% set version = "0.3.0" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 0735335fec7d70b357fa1e565dbebd892794a1d8a6a35bf47aebf640cdc4e4d6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
