{% set version = "0.5.0" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: d784441df77b2ddc37e91ed46451bd4a32f63091e1793b1bfe012de07174ad92

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6,<4
    - pip
  run:
    - python >=3.6,<4
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
