{% set version = "1.1.1" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://github.com/ioos/erddapy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 942fd45abd705679534d818e9eefda7a8ce7e1b75fdc4869b68a1f9e882cd096

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - pip
    - setuptools_scm
  run:
    - python >=3.6,<4
    - pandas >=0.20.3
    - requests

test:
  requires:
    - pip
  imports:
    - erddapy
  commands:
    - pip check

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
