{% set version = "0.1.6" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 56f1e48471f8209a395f524a0caf5730b70c4673f68ba2b1e6f98418134c8a39

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
