{% set version = "0.1.3" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 57a7118ff825788240a74bc32220fe889c6045ce90c63b20619719e9f83a7cf5

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/ocefpaf/erddapy
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
