{% set name = "erddapy" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erddapy-{{ version }}.tar.gz
  sha256: c76b115fb27a248e1a463db7358ec886b1252bde8857669679b4c507b1a1570d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - httpx
    - pandas <3,>=0.25.2
    - pytz

test:
  imports:
    - erddapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
