{% set version = "0.7.0" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 87289c428637f433161cae6385d89201938939c4119cdd11cc248fd9b53b9261

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - pip
    - setuptools_scm
  run:
    - python >=3.6,<4
    - pandas >=0.20.3
    - requests

test:
  requires:
    - pip
  imports:
    - erddapy
  commands:
    - pip check

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
