travis:
  secure:
    BINSTAR_TOKEN: ijO4706vESN17JorwIiXis3I/7ElUMlE2y5vskC+vLBzkJBal56KOx6m8WzZsonzh1WFoKHG9/1KxzXfv59wTEnRke1/YOW0GwYgyqtDRw+95g0HDGtvrvPaRBOldNw9AuUIVRExcrj2FFLho5aawunWefq5CiK4UO0e2K5lBdJ6Th5a9VPm6eXCmOkGxFZWmLGlYDSEKbRZxsDE1eGKfA/DeIboRwo7zSn+Ecp72TAAOM7tkkjboDCXyf/ybee01eFrpbM4l/ax4qCof4Fyw0Fim2xoU6L9B0TJ7QlOcRorG8owIqas2P/uHdKJ9t2iev0bRb33i7SEiQbk6Vc6C7f5YedA6M6eOQi2faaXCETRwyQGO7Ioc1OyTxKkAkgfSMQa9rulpCgVJKFCMo4WqQh3fDo0IWRCThCZs4SnxwTAIRfS8Kg0dhL15qRM6pxyjtycuzE1fZ1qcLAvyjXMHApMlGZ0/4TvJQQqLkuXMvo4kDWjMjUnKEzkeqvVWrGhDmIl2oIONiP6LgXcq9IcoZyoXSuMVVzAHiUFpwZfnVn5krIkB/5MkWmUVbQvW4DbsODMWJHWGbnZIyYaHax2bJKvL9YSSygRCwaObtwM5FTTFkZbhQJeeBkjKjRam8ezUwavXAFxIq0qRAiuFnwCi3d3Fi5PRXttt8qkstWddpw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
